
package sports;

import java.sql.*;
import demo.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class add extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    public add() {
        initComponents();
         int x=Indoor.getMaxid();
        x=x+1;
        jTextField29.setEditable(true);
        jTextField29.setText(String.valueOf(x));
         int y=outdoor.getMaxid();
        y=y+1;
        jTextField31.setEditable(true);
        jTextField31.setText(String.valueOf(y));
         int z=coach.getMaxid();
        z=z+1;
        jTextField39.setEditable(true);
        jTextField39.setText(String.valueOf(z));
         
        int b=batch.getMaxid();
        b=b+1;
        jTextField37.setEditable(true);
        jTextField37.setText(String.valueOf(b));     
        int g=pack.getMaxid();
        g=g+1;
        jTextField1.setEditable(true);
        jTextField1.setText(String.valueOf(g));
        int q=court.getMaxid();
        q=q+1;
        jTextField4.setEditable(true);
        jTextField4.setText(String.valueOf(q));
            try
        {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //Connection conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49171;databaseName=sports;integratedSecurity=true");
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","oracle");
            Statement stmt=conn.createStatement();
          
            ResultSet rs=stmt.executeQuery("select gtype from gametype");
            
            while(rs.next())
            {
            jComboBox1.addItem(rs.getString("gType"));
            }
            
        }
        catch(Exception e)
        {
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField29 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable16 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jTextField31 = new javax.swing.JTextField();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable17 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jTextField37 = new javax.swing.JTextField();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable20 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTable21 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vasu Pal\\Documents\\NetBeansProjects\\sports\\build\\classes\\project\\Shunsuke1_20080622.jpg")); // NOI18N
        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N

        jPanel1.setLayout(null);

        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField29);
        jTextField29.setBounds(290, 40, 190, 20);

        jLabel30.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Game Name:");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(140, 90, 78, 20);
        jPanel1.add(jTextField30);
        jTextField30.setBounds(290, 90, 190, 20);

        jButton57.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton57.setText("Insert");
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton57);
        jButton57.setBounds(130, 150, 65, 29);

        jButton58.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton58.setText("Update");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton58);
        jButton58.setBounds(230, 150, 75, 29);

        jButton59.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton59.setText("Delete");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton59);
        jButton59.setBounds(330, 150, 71, 29);

        jButton60.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton60.setText("Select");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton60);
        jButton60.setBounds(430, 150, 67, 29);

        jLabel29.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Game Id:");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(140, 40, 53, 20);

        jTable16.setAutoCreateRowSorter(true);
        jTable16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Game Id", "Game Name"
            }
        ));
        jTable16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable16.setRowSelectionAllowed(false);
        jTable16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable16MouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(jTable16);

        jPanel1.add(jScrollPane16);
        jScrollPane16.setBounds(10, 220, 570, 170);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/home.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(0, 0, 50, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vasu Pal\\Documents\\NetBeansProjects\\sports\\build\\classes\\project\\pool-table-balls-game.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-46, 0, 650, 620);

        jTabbedPane1.addTab("Indoor Games", jPanel1);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel31.setText("Game Id:");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel32.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel32.setText("Game Name:");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));
        jPanel4.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, -1));

        jButton61.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton61.setText("Insert");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jButton62.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton62.setText("Update");
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jButton63.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton63.setText("Delete");
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jButton64.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton64.setText("Select");
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 190, -1));

        jTable17.setAutoCreateRowSorter(true);
        jTable17.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Game Id", "Game Name"
            }
        ));
        jTable17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable17MouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(jTable17);

        jPanel4.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 570, 170));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/home.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vasu Pal\\Documents\\NetBeansProjects\\sports\\build\\classes\\project\\valuable-sports-teams.jpg")); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, -370, 1020, 970));

        jTabbedPane1.addTab("Outdoor Games", jPanel4);

        jPanel19.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel37.setText("Batch Id:");
        jPanel19.add(jLabel37);
        jLabel37.setBounds(140, 40, 110, 20);

        jLabel38.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel38.setText("Batch Type:");
        jPanel19.add(jLabel38);
        jLabel38.setBounds(140, 90, 130, 20);
        jPanel19.add(jTextField38);
        jTextField38.setBounds(290, 90, 190, 20);

        jButton73.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton73.setText("Insert");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton73);
        jButton73.setBounds(130, 150, 65, 29);

        jButton74.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton74.setText("Update");
        jButton74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton74ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton74);
        jButton74.setBounds(230, 150, 80, 29);

        jButton75.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton75.setText("Delete");
        jButton75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton75ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton75);
        jButton75.setBounds(330, 150, 80, 29);

        jButton76.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton76.setText("Select");
        jButton76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton76ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton76);
        jButton76.setBounds(430, 150, 70, 29);

        jTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField37ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField37);
        jTextField37.setBounds(290, 40, 190, 20);

        jTable20.setAutoCreateRowSorter(true);
        jTable20.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Batch Id", "Batch Name"
            }
        ));
        jTable20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable20MouseClicked(evt);
            }
        });
        jScrollPane20.setViewportView(jTable20);

        jPanel19.add(jScrollPane20);
        jScrollPane20.setBounds(10, 220, 570, 170);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/home.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton12);
        jButton12.setBounds(0, 0, 50, 30);
        jPanel19.add(jLabel15);
        jLabel15.setBounds(210, 350, 240, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vasu Pal\\Documents\\sports project\\football.jpg")); // NOI18N
        jPanel19.add(jLabel11);
        jLabel11.setBounds(-10, -130, 620, 810);

        jTabbedPane1.addTab("BatchTimings", jPanel19);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Package Id:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 123, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 190, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, -1));

        jButton1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jButton2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jButton3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jButton4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton4.setText("Select");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Package Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 123, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fee:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 190, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Package", "Fee Amount"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 570, 170));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/home.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Didsbury-Reception.jpg"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-460, -80, 190, 640));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vasu Pal\\Documents\\NetBeansProjects\\sports\\build\\classes\\project\\sports2.jpg")); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-820, -170, 1550, 790));

        jTabbedPane1.addTab("Packages", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Court Id:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 140, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 190, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Court Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, -1));

        jButton5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton5.setText("Insert");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jButton6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jButton7.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jButton8.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton8.setText("Select");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 190, -1));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Court Name"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 570, 170));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/home.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vasu Pal\\Documents\\NetBeansProjects\\sports\\build\\classes\\project\\court.jpg")); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -10, 790, 650));

        jTabbedPane1.addTab("Court", jPanel3);

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 51));
        jLabel40.setText("Coach Name:");
        jPanel20.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel41.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 51));
        jLabel41.setText("Address:");
        jPanel20.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel42.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 51));
        jLabel42.setText("Salary:");
        jPanel20.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel43.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 51));
        jLabel43.setText("Phone:");
        jPanel20.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 80, -1));

        jLabel44.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 51));
        jLabel44.setText("Gender:");
        jPanel20.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 80, -1));
        jPanel20.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 190, -1));
        jPanel20.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 190, -1));

        jLabel39.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 51));
        jLabel39.setText("Coach Id:");
        jPanel20.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));
        jPanel20.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 190, -1));
        jPanel20.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 190, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel20.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jPanel20.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        jButton77.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton77.setText("Insert");
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jButton78.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton78.setText("Update");
        jButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton78ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jButton79.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton79.setText("Delete");
        jButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton79ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        jButton80.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton80.setText("Select");
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane21.setViewportView(jTextArea1);

        jPanel20.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 190, 60));

        jLabel45.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 51));
        jLabel45.setText("Experience");
        jPanel20.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jTable21.setAutoCreateRowSorter(true);
        jTable21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Coach id", "Coach Name", "Address", "Experience", "Salary", "Phone", "Game Type", "Game", "Gender"
            }
        ));
        jTable21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable21MouseClicked(evt);
            }
        });
        jScrollPane22.setViewportView(jTable21);

        jPanel20.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 570, 170));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Game type:");
        jPanel20.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 150, -1));
        jPanel20.add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 190, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel20.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 190, -1));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel20.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 190, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Game:");
        jPanel20.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 90, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/home.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vasu Pal\\Documents\\NetBeansProjects\\sports\\build\\classes\\project\\our-research-spotlight.jpg")); // NOI18N
        jPanel20.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -30, 670, 660));

        jTabbedPane1.addTab("Coach Details", jPanel20);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        welcome a=new welcome();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jComboBox2.removeAllItems();

        String gType=(String)jComboBox1.getSelectedItem();

        try
        {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //Connection conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49171;databaseName=sports;integratedSecurity=true");

            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","oracle");
            Statement stmt=conn.createStatement();

            if(gType.equals("Indoor"))
            {
                ResultSet rs=stmt.executeQuery("select gname from indoor_master");

                while(rs.next())
                {
                    jComboBox2.addItem(rs.getString("gname"));

                }

            }
            else{
                ResultSet rso=stmt.executeQuery("select gname from outdoor_master");

                while(rso.next())
                {
                    jComboBox2.addItem(rso.getString("gname"));
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, ""+e);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable21MouseClicked
        int cols=jTable21.getColumnCount();
        String aa[]=new String[cols];

        for(int i=0;i<cols;i++)
        {
            aa[i]=jTable21.getValueAt(jTable21.getSelectedRow(), i).toString();
        }
        jTextField39.setEditable(true);
        jTextField39.setText(aa[0]);
        jTextField40.setText(aa[1]);
        jTextField43.setText(aa[5]);
        jTextArea1.setText(aa[2]);
        jTextField41.setText(aa[4]);
        jTextField42.setText(aa[3]);
    }//GEN-LAST:event_jTable21MouseClicked

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        String str="select * from coach_master";
        DefaultTableModel amodel=(DefaultTableModel)jTable21.getModel();
        amodel.setRowCount(0);
        try{
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //Connection conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49171;databaseName=sports;integratedSecurity=true");
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","oracle");
            String colhead[]={"Coach Id", "Name","Address","Experience","Salary","Contact","Game Type","Game","Gender"};

            amodel.setColumnIdentifiers(colhead);
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(str);

            ResultSetMetaData rsmd=rs.getMetaData();
            int cols=rsmd.getColumnCount();
            while(rs.next())
            {
                Object[] obj=new Object[cols];

                for(int i=0;i<cols;i++)
                {
                    obj[i]=rs.getObject(i+1);

                }
                amodel.addRow(obj);
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton80ActionPerformed

    private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton79ActionPerformed

        coachprop co=new coachprop();

        int id=Integer.parseInt(jTextField39.getText());

        co.setId(id);

        demo.coach d=new coach();
        d.deleteData(co);
    }//GEN-LAST:event_jButton79ActionPerformed

    private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton78ActionPerformed
        coachprop co=new coachprop();
        String gender="";
        if(jRadioButton1.isSelected()==true)
        {
            gender="Male";
        }
        else

        {
            gender="Female";
        }
        String gametype=jComboBox1.getSelectedItem().toString();
        String game=jComboBox2.getSelectedItem().toString();
        String name=jTextField40.getText().toString();
        int id=Integer.parseInt(jTextField39.getText());
        String address=jTextArea1.getText().toString();
        int experience=Integer.parseInt(jTextField43.getText());
        int salary=Integer.parseInt(jTextField41.getText());
        String phone=(jTextField42.getText());

        co.setId(id);
        co.setName(name);
        co.setAddress(address);
        co.setExperience(experience);
        co.setSalary(salary);
        co.setGender(gender);
        co.setContact(phone);
        co.setGametype(gametype);
        co.setGame(game);
        demo.coach d=new coach();
        d.updateData(co);
    }//GEN-LAST:event_jButton78ActionPerformed

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed

        coachprop co=new coachprop();
        String gender="";
        if(jRadioButton1.isSelected()==true)
        {
            gender="Male";
        }
        else
        {
            gender="Female";
        }
        String gametype=jComboBox1.getSelectedItem().toString();
        String game=jComboBox2.getSelectedItem().toString();
        String name=jTextField40.getText().toString();
        int id=Integer.parseInt(jTextField39.getText());
        String address=jTextArea1.getText().toString();
        int experience=Integer.parseInt(jTextField43.getText());
        int salary=Integer.parseInt(jTextField41.getText());
        String phone=(jTextField42.getText());

        co.setId(id);
        co.setName(name);
        co.setAddress(address);
        co.setExperience(experience);
        co.setSalary(salary);
        co.setGender(gender);
        co.setContact(phone);
        co.setGametype(gametype);
        co.setGame(game);

        demo.coach d=new coach();
        d.insertData(co);
    }//GEN-LAST:event_jButton77ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        welcome a=new welcome();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int cols=jTable2.getColumnCount();
        String aa[]=new String[cols];

        for(int i=0;i<cols;i++)
        {
            aa[i]=jTable2.getValueAt(jTable2.getSelectedRow(), i).toString();
        }
        jTextField4.setEditable(true);
        jTextField4.setText(aa[0]);
        jTextField5.setText(aa[1]);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String str="select * from court_master";
        DefaultTableModel amodel=(DefaultTableModel)jTable2.getModel();
        amodel.setRowCount(0);

        try{
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //Connection conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49171;databaseName=sports;integratedSecurity=true");
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","oracle");
            String colhead[]={"court Id", "Court Name"};

            amodel.setColumnIdentifiers(colhead);
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(str);

            ResultSetMetaData rsmd=rs.getMetaData();
            int cols=rsmd.getColumnCount();
            while(rs.next())
            {
                Object[] obj=new Object[cols];

                for(int i=0;i<cols;i++)
                {
                    obj[i]=rs.getObject(i+1);

                }
                amodel.addRow(obj);
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        courtprop p=new courtprop();

        //  String name=jTextField5.getText().toString();
        int id=Integer.parseInt(jTextField4.getText());

        //  p.setName(name);
        p.setId(id);

        demo.court d=new court();
        d.deleteData(p);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        courtprop p=new courtprop();

        String name=jTextField5.getText().toString();
        int id=Integer.parseInt(jTextField4.getText());

        p.setName(name);
        p.setId(id);

        demo.court d=new court();
        d.updateData(p);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        courtprop p=new courtprop();

        String name=jTextField5.getText().toString();
        int id=Integer.parseInt(jTextField4.getText());

        p.setName(name);
        p.setId(id);

        demo.court d=new court();
        d.insertData(p);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        welcome a=new welcome();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int cols=jTable1.getColumnCount();
        String aa[]=new String[cols];

        for(int i=0;i<cols;i++)
        {
            aa[i]=jTable1.getValueAt(jTable1.getSelectedRow(), i).toString();
        }
        jTextField1.setEditable(true);
        jTextField1.setText(aa[0]);
        jTextField2.setText(aa[1]);
        jTextField3.setText(aa[2]);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String str="select * from pack_master";
        DefaultTableModel amodel=(DefaultTableModel)jTable1.getModel();
        amodel.setRowCount(0);

        try{
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //Connection conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49171;databaseName=sports;integratedSecurity=true");
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","oracle");
            String colhead[]={"Id", "Package","Fee Amount"};

            amodel.setColumnIdentifiers(colhead);
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(str);

            ResultSetMetaData rsmd=rs.getMetaData();
            int cols=rsmd.getColumnCount();
            while(rs.next())
            {
                Object[] obj=new Object[cols];

                for(int i=0;i<cols;i++)
                {
                    obj[i]=rs.getObject(i+1);

                }
                amodel.addRow(obj);
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        packprop g=new packprop();
        int id=Integer.parseInt(jTextField1.getText());
        //    String pack=jTextField2.getText().toString();
        //    int amount=Integer.parseInt(jTextField3.getText());
        g.setId(id);
        //   g.setPack(pack);
        //    g.setAmount(amount);

        demo.pack d=new pack();
        d.deleteData(g);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        packprop g=new packprop();
        int id=Integer.parseInt(jTextField1.getText());
        String pack=jTextField2.getText().toString();
        int amount=Integer.parseInt(jTextField3.getText());
        g.setId(id);
        g.setPack(pack);
        g.setAmount(amount);

        demo.pack d=new pack();
        d.updateData(g);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        packprop g=new packprop();
        int id=Integer.parseInt(jTextField1.getText());
        String pack=jTextField2.getText().toString();
        int amount=Integer.parseInt(jTextField3.getText());
        g.setId(id);
        g.setPack(pack);
        g.setAmount(amount);

        demo.pack d=new pack();
        d.insertData(g);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        welcome a=new welcome();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTable20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable20MouseClicked
        int cols=jTable20.getColumnCount();
        String aa[]=new String[cols];

        for(int i=0;i<cols;i++)
        {
            aa[i]=jTable20.getValueAt(jTable20.getSelectedRow(), i).toString();
        }
        jTextField37.setEditable(true);
        jTextField38.setText(aa[0]);
        jTextField38.setText(aa[1]);
    }//GEN-LAST:event_jTable20MouseClicked

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jButton76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton76ActionPerformed
        String str="select * from batch_master";
        DefaultTableModel amodel=(DefaultTableModel)jTable20.getModel();
        amodel.setRowCount(0);

        try{
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //Connection conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49171;databaseName=sports;integratedSecurity=true");
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","oracle");
            String colhead[]={"Batch Id", "Batch Name"};

            amodel.setColumnIdentifiers(colhead);
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(str);

            ResultSetMetaData rsmd=rs.getMetaData();
            int cols=rsmd.getColumnCount();
            while(rs.next())
            {
                Object[] obj=new Object[cols];

                for(int i=0;i<cols;i++)
                {
                    obj[i]=rs.getObject(i+1);

                }
                amodel.addRow(obj);
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton76ActionPerformed

    private void jButton75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton75ActionPerformed
        batchprop p=new batchprop();

        // String name=jTextField38.getText().toString();
        int id=Integer.parseInt(jTextField37.getText());

        // p.setName(name);
        p.setId(id);

        demo.batch d=new batch();
        d.deleteData(p);
    }//GEN-LAST:event_jButton75ActionPerformed

    private void jButton74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton74ActionPerformed
        batchprop p=new batchprop();

        String name=jTextField38.getText().toString();
        int id=Integer.parseInt(jTextField37.getText());

        p.setName(name);
        p.setId(id);

        demo.batch d=new batch();
        d.updateData(p);
    }//GEN-LAST:event_jButton74ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        batchprop p=new batchprop();

        String name=jTextField38.getText().toString();
        int id=Integer.parseInt(jTextField37.getText());

        p.setName(name);
        p.setId(id);

        demo.batch d=new batch();
        d.insertData(p);
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        welcome a=new welcome();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable17MouseClicked
        int cols=jTable17.getColumnCount();
        String aa[]=new String[cols];

        for(int i=0;i<cols;i++)
        {
            aa[i]=jTable17.getValueAt(jTable17.getSelectedRow(), i).toString();
        }
        jTextField31.setEditable(true);
        jTextField31.setText(aa[0]);
        jTextField32.setText(aa[1]);
    }//GEN-LAST:event_jTable17MouseClicked

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        String str="select * from outdoor_master";
        DefaultTableModel amodel=(DefaultTableModel)jTable17.getModel();
        amodel.setRowCount(0);
        try{
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //Connection conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49171;databaseName=sports;integratedSecurity=true");
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","oracle");
            String colhead[]={"Game Id", "Game Name"};

            amodel.setColumnIdentifiers(colhead);
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(str);

            ResultSetMetaData rsmd=rs.getMetaData();
            int cols=rsmd.getColumnCount();
            while(rs.next())
            {
                Object[] obj=new Object[cols];

                for(int i=0;i<cols;i++)
                {
                    obj[i]=rs.getObject(i+1);

                }
                amodel.addRow(obj);
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        outprop out=new outprop();

        String name=jTextField32.getText().toString();
        int id=Integer.parseInt(jTextField31.getText());

        out.setName(name);
        out.setId(id);

        demo.outdoor o=new outdoor();
        o.deleteData(out);
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        outprop out=new outprop();

        String name=jTextField32.getText().toString();
        int id=Integer.parseInt(jTextField31.getText());

        out.setName(name);
        out.setId(id);

        demo.outdoor o=new outdoor();
        o.updateData(out);
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed

        outprop out=new outprop();

        String name=jTextField32.getText().toString();
        int id=Integer.parseInt(jTextField31.getText());

        out.setName(name);
        out.setId(id);

        demo.outdoor o=new outdoor();
        o.insertData(out);
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        welcome a=new welcome();
        a.show();
        this.hide();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTable16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable16MouseClicked
        int cols=jTable16.getColumnCount();
        String aa[]=new String[cols];

        for(int i=0;i<cols;i++)
        {
            aa[i]=jTable16.getValueAt(jTable16.getSelectedRow(), i).toString();
        }
        jTextField29.setEditable(true);
        jTextField29.setText(aa[0]);
        jTextField30.setText(aa[1]);
    }//GEN-LAST:event_jTable16MouseClicked

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        String str="select * from indoor_master";
        DefaultTableModel amodel=(DefaultTableModel)jTable16.getModel();
        amodel.setRowCount(0);

        try{
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            //Connection conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49171;databaseName=sports;integratedSecurity=true");
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","hr","oracle");
            String colhead[]={"Game Id", "Game Name"};

            amodel.setColumnIdentifiers(colhead);
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(str);

            ResultSetMetaData rsmd=rs.getMetaData();
            int cols=rsmd.getColumnCount();
            while(rs.next()) 
            {
                Object[] obj=new Object[cols];

                for(int i=0;i<cols;i++)
                {
                    obj[i]=rs.getObject(i+1);

                }
                amodel.addRow(obj);
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        prop p=new prop();

        //String name=jTextField2.getText().toString();
        int id=Integer.parseInt(jTextField29.getText());

        //p.setName(name);
        p.setId(id);

        demo.Indoor d=new Indoor();
        d.deleteData(p);
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        prop p=new prop();

        String name=jTextField30.getText().toString();
        int id=Integer.parseInt(jTextField29.getText());

        p.setName(name);
        p.setId(id);

        demo.Indoor d=new Indoor();
        d.updateData(p);
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed

        prop p=new prop();

        String name=jTextField30.getText().toString();
        int id=Integer.parseInt(jTextField29.getText());

        p.setName(name);
        p.setId(id);

        demo.Indoor d=new Indoor();
        d.insertData(p);
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable16;
    private javax.swing.JTable jTable17;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable20;
    private javax.swing.JTable jTable21;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
